# replace @hostname with the current server domain name
@hostname = localhost
@port = 2000
@protocol = http
@host = {{hostname}}:{{port}}
@device = NDZA470158
@test_case = TC1
@username = "xyz"
@email = "ry@techm.com"
@appUrl = localhost
###

# @name connect

POST {{protocol}}://{{host}}/api/diag
Content-Type: application/json

{
  "serial": "{{device}}",
  "appUrl": "{{appUrl}}"
}

###

@id = {{connect.response.body.data.id}}

# @name start_log

POST {{protocol}}://{{host}}/api/logs
Content-Type: application/json

{
  "id": "{{id}}"
}

###

@log_id = {{start_log.response.body.data.logId}}

# @name stop_log

DELETE {{protocol}}://{{host}}/api/logs/{{log_id}}

###

# @name disconnect

DELETE {{protocol}}://{{host}}/api/diag/{{id}}

###

###

# @name parse_log

POST {{protocol}}://{{host}}/api/logs/{{log_id}}/parse
Content-Type: application/json

###

# @name process_log

POST {{protocol}}://{{host}}/api/logs/{{log_id}}/process
Content-Type: application/json

{
  "test_case": "{{test_case}}"
}

###
# not implemented

# @name get_log

GET {{protocol}}://{{host}}/api/logs/{{log_id}}