# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qxdm.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='qxdm.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nqxdm.proto\"&\n\x0e\x43onnectRequest\x12\x14\n\x0c\x64\x65vice_index\x18\x01 \x01(\r\"2\n\x0f\x43onnectResponse\x12\x1f\n\x05state\x18\x01 \x01(\x0e\x32\x10.ConnectionState\")\n\x11\x44isconnectRequest\x12\x14\n\x0c\x64\x65vice_index\x18\x01 \x01(\r\"5\n\x12\x44isconnectResponse\x12\x1f\n\x05state\x18\x01 \x01(\x0e\x32\x10.ConnectionState\"\'\n\x0fStartLogRequest\x12\x14\n\x0c\x64\x65vice_index\x18\x01 \x01(\r\"\x12\n\x10StartLogResponse\"&\n\x0eSaveLogRequest\x12\x14\n\x0c\x64\x65vice_index\x18\x01 \x01(\r\"\x1f\n\x0fSaveLogResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c*2\n\x0f\x43onnectionState\x12\x10\n\x0c\x44ISCONNECTED\x10\x00\x12\r\n\tCONNECTED\x10\x01\x32\xd4\x01\n\x04QXDM\x12.\n\x07\x43onnect\x12\x0f.ConnectRequest\x1a\x10.ConnectResponse\"\x00\x12\x37\n\nDisconnect\x12\x12.DisconnectRequest\x1a\x13.DisconnectResponse\"\x00\x12\x31\n\x08StartLog\x12\x10.StartLogRequest\x1a\x11.StartLogResponse\"\x00\x12\x30\n\x07SaveLog\x12\x0f.SaveLogRequest\x1a\x10.SaveLogResponse\"\x00\x30\x01\x62\x06proto3')
)

_CONNECTIONSTATE = _descriptor.EnumDescriptor(
  name='ConnectionState',
  full_name='ConnectionState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DISCONNECTED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONNECTED', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=338,
  serialized_end=388,
)
_sym_db.RegisterEnumDescriptor(_CONNECTIONSTATE)

ConnectionState = enum_type_wrapper.EnumTypeWrapper(_CONNECTIONSTATE)
DISCONNECTED = 0
CONNECTED = 1



_CONNECTREQUEST = _descriptor.Descriptor(
  name='ConnectRequest',
  full_name='ConnectRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_index', full_name='ConnectRequest.device_index', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=52,
)


_CONNECTRESPONSE = _descriptor.Descriptor(
  name='ConnectResponse',
  full_name='ConnectResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='ConnectResponse.state', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=104,
)


_DISCONNECTREQUEST = _descriptor.Descriptor(
  name='DisconnectRequest',
  full_name='DisconnectRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_index', full_name='DisconnectRequest.device_index', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=147,
)


_DISCONNECTRESPONSE = _descriptor.Descriptor(
  name='DisconnectResponse',
  full_name='DisconnectResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='DisconnectResponse.state', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=202,
)


_STARTLOGREQUEST = _descriptor.Descriptor(
  name='StartLogRequest',
  full_name='StartLogRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_index', full_name='StartLogRequest.device_index', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=243,
)


_STARTLOGRESPONSE = _descriptor.Descriptor(
  name='StartLogResponse',
  full_name='StartLogResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=245,
  serialized_end=263,
)


_SAVELOGREQUEST = _descriptor.Descriptor(
  name='SaveLogRequest',
  full_name='SaveLogRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_index', full_name='SaveLogRequest.device_index', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=265,
  serialized_end=303,
)


_SAVELOGRESPONSE = _descriptor.Descriptor(
  name='SaveLogResponse',
  full_name='SaveLogResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='SaveLogResponse.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=305,
  serialized_end=336,
)

_CONNECTRESPONSE.fields_by_name['state'].enum_type = _CONNECTIONSTATE
_DISCONNECTRESPONSE.fields_by_name['state'].enum_type = _CONNECTIONSTATE
DESCRIPTOR.message_types_by_name['ConnectRequest'] = _CONNECTREQUEST
DESCRIPTOR.message_types_by_name['ConnectResponse'] = _CONNECTRESPONSE
DESCRIPTOR.message_types_by_name['DisconnectRequest'] = _DISCONNECTREQUEST
DESCRIPTOR.message_types_by_name['DisconnectResponse'] = _DISCONNECTRESPONSE
DESCRIPTOR.message_types_by_name['StartLogRequest'] = _STARTLOGREQUEST
DESCRIPTOR.message_types_by_name['StartLogResponse'] = _STARTLOGRESPONSE
DESCRIPTOR.message_types_by_name['SaveLogRequest'] = _SAVELOGREQUEST
DESCRIPTOR.message_types_by_name['SaveLogResponse'] = _SAVELOGRESPONSE
DESCRIPTOR.enum_types_by_name['ConnectionState'] = _CONNECTIONSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConnectRequest = _reflection.GeneratedProtocolMessageType('ConnectRequest', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTREQUEST,
  '__module__' : 'qxdm_pb2'
  # @@protoc_insertion_point(class_scope:ConnectRequest)
  })
_sym_db.RegisterMessage(ConnectRequest)

ConnectResponse = _reflection.GeneratedProtocolMessageType('ConnectResponse', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTRESPONSE,
  '__module__' : 'qxdm_pb2'
  # @@protoc_insertion_point(class_scope:ConnectResponse)
  })
_sym_db.RegisterMessage(ConnectResponse)

DisconnectRequest = _reflection.GeneratedProtocolMessageType('DisconnectRequest', (_message.Message,), {
  'DESCRIPTOR' : _DISCONNECTREQUEST,
  '__module__' : 'qxdm_pb2'
  # @@protoc_insertion_point(class_scope:DisconnectRequest)
  })
_sym_db.RegisterMessage(DisconnectRequest)

DisconnectResponse = _reflection.GeneratedProtocolMessageType('DisconnectResponse', (_message.Message,), {
  'DESCRIPTOR' : _DISCONNECTRESPONSE,
  '__module__' : 'qxdm_pb2'
  # @@protoc_insertion_point(class_scope:DisconnectResponse)
  })
_sym_db.RegisterMessage(DisconnectResponse)

StartLogRequest = _reflection.GeneratedProtocolMessageType('StartLogRequest', (_message.Message,), {
  'DESCRIPTOR' : _STARTLOGREQUEST,
  '__module__' : 'qxdm_pb2'
  # @@protoc_insertion_point(class_scope:StartLogRequest)
  })
_sym_db.RegisterMessage(StartLogRequest)

StartLogResponse = _reflection.GeneratedProtocolMessageType('StartLogResponse', (_message.Message,), {
  'DESCRIPTOR' : _STARTLOGRESPONSE,
  '__module__' : 'qxdm_pb2'
  # @@protoc_insertion_point(class_scope:StartLogResponse)
  })
_sym_db.RegisterMessage(StartLogResponse)

SaveLogRequest = _reflection.GeneratedProtocolMessageType('SaveLogRequest', (_message.Message,), {
  'DESCRIPTOR' : _SAVELOGREQUEST,
  '__module__' : 'qxdm_pb2'
  # @@protoc_insertion_point(class_scope:SaveLogRequest)
  })
_sym_db.RegisterMessage(SaveLogRequest)

SaveLogResponse = _reflection.GeneratedProtocolMessageType('SaveLogResponse', (_message.Message,), {
  'DESCRIPTOR' : _SAVELOGRESPONSE,
  '__module__' : 'qxdm_pb2'
  # @@protoc_insertion_point(class_scope:SaveLogResponse)
  })
_sym_db.RegisterMessage(SaveLogResponse)



_QXDM = _descriptor.ServiceDescriptor(
  name='QXDM',
  full_name='QXDM',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=391,
  serialized_end=603,
  methods=[
  _descriptor.MethodDescriptor(
    name='Connect',
    full_name='QXDM.Connect',
    index=0,
    containing_service=None,
    input_type=_CONNECTREQUEST,
    output_type=_CONNECTRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Disconnect',
    full_name='QXDM.Disconnect',
    index=1,
    containing_service=None,
    input_type=_DISCONNECTREQUEST,
    output_type=_DISCONNECTRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StartLog',
    full_name='QXDM.StartLog',
    index=2,
    containing_service=None,
    input_type=_STARTLOGREQUEST,
    output_type=_STARTLOGRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SaveLog',
    full_name='QXDM.SaveLog',
    index=3,
    containing_service=None,
    input_type=_SAVELOGREQUEST,
    output_type=_SAVELOGRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_QXDM)

DESCRIPTOR.services_by_name['QXDM'] = _QXDM

# @@protoc_insertion_point(module_scope)
