# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import qxdm_pb2 as qxdm__pb2


class QXDMStub(object):
  """The QXDM service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.LaunchApp = channel.unary_unary(
        '/QXDM/LaunchApp',
        request_serializer=qxdm__pb2.LaunchAppRequest.SerializeToString,
        response_deserializer=qxdm__pb2.LaunchAppResponse.FromString,
        )
    self.ConnectDevice = channel.unary_unary(
        '/QXDM/ConnectDevice',
        request_serializer=qxdm__pb2.ConnectDeviceRequest.SerializeToString,
        response_deserializer=qxdm__pb2.ConnectDeviceResponse.FromString,
        )
    self.DisconnectDevice = channel.unary_unary(
        '/QXDM/DisconnectDevice',
        request_serializer=qxdm__pb2.DisconnectDeviceRequest.SerializeToString,
        response_deserializer=qxdm__pb2.DisconnectDeviceResponse.FromString,
        )
    self.StartLog = channel.unary_unary(
        '/QXDM/StartLog',
        request_serializer=qxdm__pb2.StartLogRequest.SerializeToString,
        response_deserializer=qxdm__pb2.StartLogResponse.FromString,
        )
    self.SaveLog = channel.unary_stream(
        '/QXDM/SaveLog',
        request_serializer=qxdm__pb2.SaveLogRequest.SerializeToString,
        response_deserializer=qxdm__pb2.SaveLogResponse.FromString,
        )
    self.QuitApp = channel.unary_unary(
        '/QXDM/QuitApp',
        request_serializer=qxdm__pb2.QuitAppRequest.SerializeToString,
        response_deserializer=qxdm__pb2.QuitAppResponse.FromString,
        )


class QXDMServicer(object):
  """The QXDM service definition.
  """

  def LaunchApp(self, request, context):
    """Launches an QXDM process
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ConnectDevice(self, request, context):
    """Connects a device to the QXDM process
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DisconnectDevice(self, request, context):
    """Disconnects a device from the QXDM process
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StartLog(self, request, context):
    """Start logging on a QXDM process  
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SaveLog(self, request, context):
    """Save logs on a QXDM process
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def QuitApp(self, request, context):
    """Quit a running QXDM process
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_QXDMServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'LaunchApp': grpc.unary_unary_rpc_method_handler(
          servicer.LaunchApp,
          request_deserializer=qxdm__pb2.LaunchAppRequest.FromString,
          response_serializer=qxdm__pb2.LaunchAppResponse.SerializeToString,
      ),
      'ConnectDevice': grpc.unary_unary_rpc_method_handler(
          servicer.ConnectDevice,
          request_deserializer=qxdm__pb2.ConnectDeviceRequest.FromString,
          response_serializer=qxdm__pb2.ConnectDeviceResponse.SerializeToString,
      ),
      'DisconnectDevice': grpc.unary_unary_rpc_method_handler(
          servicer.DisconnectDevice,
          request_deserializer=qxdm__pb2.DisconnectDeviceRequest.FromString,
          response_serializer=qxdm__pb2.DisconnectDeviceResponse.SerializeToString,
      ),
      'StartLog': grpc.unary_unary_rpc_method_handler(
          servicer.StartLog,
          request_deserializer=qxdm__pb2.StartLogRequest.FromString,
          response_serializer=qxdm__pb2.StartLogResponse.SerializeToString,
      ),
      'SaveLog': grpc.unary_stream_rpc_method_handler(
          servicer.SaveLog,
          request_deserializer=qxdm__pb2.SaveLogRequest.FromString,
          response_serializer=qxdm__pb2.SaveLogResponse.SerializeToString,
      ),
      'QuitApp': grpc.unary_unary_rpc_method_handler(
          servicer.QuitApp,
          request_deserializer=qxdm__pb2.QuitAppRequest.FromString,
          response_serializer=qxdm__pb2.QuitAppResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'QXDM', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
