# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qxdm.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='qxdm.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nqxdm.proto\"&\n\x0e\x43onnectRequest\x12\x14\n\x0c\x64\x65vice_index\x18\x01 \x01(\r\"2\n\x0f\x43onnectResponse\x12\x1f\n\x05state\x18\x01 \x01(\x0e\x32\x10.ConnectionState\")\n\x11\x44isconnectRequest\x12\x14\n\x0c\x64\x65vice_index\x18\x01 \x01(\r\"5\n\x12\x44isconnectResponse\x12\x1f\n\x05state\x18\x01 \x01(\x0e\x32\x10.ConnectionState\"\'\n\x0fStartLogRequest\x12\x14\n\x0c\x64\x65vice_index\x18\x01 \x01(\r\"\x12\n\x10StartLogResponse\"9\n\x0eSaveLogRequest\x12\x14\n\x0c\x64\x65vice_index\x18\x01 \x01(\r\x12\x11\n\tsend_file\x18\x02 \x01(\x08\"I\n\x0fSaveLogResponse\x12\x12\n\x08\x66ilename\x18\x01 \x01(\tH\x00\x12\x0e\n\x04\x64\x61ta\x18\x02 \x01(\x0cH\x00\x42\x12\n\x10\x66ilename_or_data\"G\n\x0fParseLogRequest\x12\x16\n\x0einput_filename\x18\x01 \x01(\t\x12\x1c\n\x14test_config_filename\x18\x02 \x01(\t\" \n\x10ParseLogResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x0f\n\rStatusRequest\"\x1f\n\x0eStatusResponse\x12\r\n\x05ready\x18\x01 \x01(\x08*2\n\x0f\x43onnectionState\x12\x10\n\x0c\x44ISCONNECTED\x10\x00\x12\r\n\tCONNECTED\x10\x01\x32\xb6\x02\n\x04QXDM\x12.\n\x07\x43onnect\x12\x0f.ConnectRequest\x1a\x10.ConnectResponse\"\x00\x12\x37\n\nDisconnect\x12\x12.DisconnectRequest\x1a\x13.DisconnectResponse\"\x00\x12\x31\n\x08StartLog\x12\x10.StartLogRequest\x1a\x11.StartLogResponse\"\x00\x12\x30\n\x07SaveLog\x12\x0f.SaveLogRequest\x1a\x10.SaveLogResponse\"\x00\x30\x01\x12\x33\n\x08ParseLog\x12\x10.ParseLogRequest\x1a\x11.ParseLogResponse\"\x00\x30\x01\x12+\n\x06Status\x12\x0e.StatusRequest\x1a\x0f.StatusResponse\"\x00\x62\x06proto3'
)

_CONNECTIONSTATE = _descriptor.EnumDescriptor(
  name='ConnectionState',
  full_name='ConnectionState',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DISCONNECTED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CONNECTED', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=556,
  serialized_end=606,
)
_sym_db.RegisterEnumDescriptor(_CONNECTIONSTATE)

ConnectionState = enum_type_wrapper.EnumTypeWrapper(_CONNECTIONSTATE)
DISCONNECTED = 0
CONNECTED = 1



_CONNECTREQUEST = _descriptor.Descriptor(
  name='ConnectRequest',
  full_name='ConnectRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_index', full_name='ConnectRequest.device_index', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=52,
)


_CONNECTRESPONSE = _descriptor.Descriptor(
  name='ConnectResponse',
  full_name='ConnectResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='ConnectResponse.state', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=104,
)


_DISCONNECTREQUEST = _descriptor.Descriptor(
  name='DisconnectRequest',
  full_name='DisconnectRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_index', full_name='DisconnectRequest.device_index', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=147,
)


_DISCONNECTRESPONSE = _descriptor.Descriptor(
  name='DisconnectResponse',
  full_name='DisconnectResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='DisconnectResponse.state', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=202,
)


_STARTLOGREQUEST = _descriptor.Descriptor(
  name='StartLogRequest',
  full_name='StartLogRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_index', full_name='StartLogRequest.device_index', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=243,
)


_STARTLOGRESPONSE = _descriptor.Descriptor(
  name='StartLogResponse',
  full_name='StartLogResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=245,
  serialized_end=263,
)


_SAVELOGREQUEST = _descriptor.Descriptor(
  name='SaveLogRequest',
  full_name='SaveLogRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_index', full_name='SaveLogRequest.device_index', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='send_file', full_name='SaveLogRequest.send_file', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=265,
  serialized_end=322,
)


_SAVELOGRESPONSE = _descriptor.Descriptor(
  name='SaveLogResponse',
  full_name='SaveLogResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='filename', full_name='SaveLogResponse.filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='SaveLogResponse.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='filename_or_data', full_name='SaveLogResponse.filename_or_data',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=324,
  serialized_end=397,
)


_PARSELOGREQUEST = _descriptor.Descriptor(
  name='ParseLogRequest',
  full_name='ParseLogRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='input_filename', full_name='ParseLogRequest.input_filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='test_config_filename', full_name='ParseLogRequest.test_config_filename', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=399,
  serialized_end=470,
)


_PARSELOGRESPONSE = _descriptor.Descriptor(
  name='ParseLogResponse',
  full_name='ParseLogResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='ParseLogResponse.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=472,
  serialized_end=504,
)


_STATUSREQUEST = _descriptor.Descriptor(
  name='StatusRequest',
  full_name='StatusRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=506,
  serialized_end=521,
)


_STATUSRESPONSE = _descriptor.Descriptor(
  name='StatusResponse',
  full_name='StatusResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ready', full_name='StatusResponse.ready', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=523,
  serialized_end=554,
)

_CONNECTRESPONSE.fields_by_name['state'].enum_type = _CONNECTIONSTATE
_DISCONNECTRESPONSE.fields_by_name['state'].enum_type = _CONNECTIONSTATE
_SAVELOGRESPONSE.oneofs_by_name['filename_or_data'].fields.append(
  _SAVELOGRESPONSE.fields_by_name['filename'])
_SAVELOGRESPONSE.fields_by_name['filename'].containing_oneof = _SAVELOGRESPONSE.oneofs_by_name['filename_or_data']
_SAVELOGRESPONSE.oneofs_by_name['filename_or_data'].fields.append(
  _SAVELOGRESPONSE.fields_by_name['data'])
_SAVELOGRESPONSE.fields_by_name['data'].containing_oneof = _SAVELOGRESPONSE.oneofs_by_name['filename_or_data']
DESCRIPTOR.message_types_by_name['ConnectRequest'] = _CONNECTREQUEST
DESCRIPTOR.message_types_by_name['ConnectResponse'] = _CONNECTRESPONSE
DESCRIPTOR.message_types_by_name['DisconnectRequest'] = _DISCONNECTREQUEST
DESCRIPTOR.message_types_by_name['DisconnectResponse'] = _DISCONNECTRESPONSE
DESCRIPTOR.message_types_by_name['StartLogRequest'] = _STARTLOGREQUEST
DESCRIPTOR.message_types_by_name['StartLogResponse'] = _STARTLOGRESPONSE
DESCRIPTOR.message_types_by_name['SaveLogRequest'] = _SAVELOGREQUEST
DESCRIPTOR.message_types_by_name['SaveLogResponse'] = _SAVELOGRESPONSE
DESCRIPTOR.message_types_by_name['ParseLogRequest'] = _PARSELOGREQUEST
DESCRIPTOR.message_types_by_name['ParseLogResponse'] = _PARSELOGRESPONSE
DESCRIPTOR.message_types_by_name['StatusRequest'] = _STATUSREQUEST
DESCRIPTOR.message_types_by_name['StatusResponse'] = _STATUSRESPONSE
DESCRIPTOR.enum_types_by_name['ConnectionState'] = _CONNECTIONSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConnectRequest = _reflection.GeneratedProtocolMessageType('ConnectRequest', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTREQUEST,
  '__module__' : 'qxdm_pb2'
  # @@protoc_insertion_point(class_scope:ConnectRequest)
  })
_sym_db.RegisterMessage(ConnectRequest)

ConnectResponse = _reflection.GeneratedProtocolMessageType('ConnectResponse', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTRESPONSE,
  '__module__' : 'qxdm_pb2'
  # @@protoc_insertion_point(class_scope:ConnectResponse)
  })
_sym_db.RegisterMessage(ConnectResponse)

DisconnectRequest = _reflection.GeneratedProtocolMessageType('DisconnectRequest', (_message.Message,), {
  'DESCRIPTOR' : _DISCONNECTREQUEST,
  '__module__' : 'qxdm_pb2'
  # @@protoc_insertion_point(class_scope:DisconnectRequest)
  })
_sym_db.RegisterMessage(DisconnectRequest)

DisconnectResponse = _reflection.GeneratedProtocolMessageType('DisconnectResponse', (_message.Message,), {
  'DESCRIPTOR' : _DISCONNECTRESPONSE,
  '__module__' : 'qxdm_pb2'
  # @@protoc_insertion_point(class_scope:DisconnectResponse)
  })
_sym_db.RegisterMessage(DisconnectResponse)

StartLogRequest = _reflection.GeneratedProtocolMessageType('StartLogRequest', (_message.Message,), {
  'DESCRIPTOR' : _STARTLOGREQUEST,
  '__module__' : 'qxdm_pb2'
  # @@protoc_insertion_point(class_scope:StartLogRequest)
  })
_sym_db.RegisterMessage(StartLogRequest)

StartLogResponse = _reflection.GeneratedProtocolMessageType('StartLogResponse', (_message.Message,), {
  'DESCRIPTOR' : _STARTLOGRESPONSE,
  '__module__' : 'qxdm_pb2'
  # @@protoc_insertion_point(class_scope:StartLogResponse)
  })
_sym_db.RegisterMessage(StartLogResponse)

SaveLogRequest = _reflection.GeneratedProtocolMessageType('SaveLogRequest', (_message.Message,), {
  'DESCRIPTOR' : _SAVELOGREQUEST,
  '__module__' : 'qxdm_pb2'
  # @@protoc_insertion_point(class_scope:SaveLogRequest)
  })
_sym_db.RegisterMessage(SaveLogRequest)

SaveLogResponse = _reflection.GeneratedProtocolMessageType('SaveLogResponse', (_message.Message,), {
  'DESCRIPTOR' : _SAVELOGRESPONSE,
  '__module__' : 'qxdm_pb2'
  # @@protoc_insertion_point(class_scope:SaveLogResponse)
  })
_sym_db.RegisterMessage(SaveLogResponse)

ParseLogRequest = _reflection.GeneratedProtocolMessageType('ParseLogRequest', (_message.Message,), {
  'DESCRIPTOR' : _PARSELOGREQUEST,
  '__module__' : 'qxdm_pb2'
  # @@protoc_insertion_point(class_scope:ParseLogRequest)
  })
_sym_db.RegisterMessage(ParseLogRequest)

ParseLogResponse = _reflection.GeneratedProtocolMessageType('ParseLogResponse', (_message.Message,), {
  'DESCRIPTOR' : _PARSELOGRESPONSE,
  '__module__' : 'qxdm_pb2'
  # @@protoc_insertion_point(class_scope:ParseLogResponse)
  })
_sym_db.RegisterMessage(ParseLogResponse)

StatusRequest = _reflection.GeneratedProtocolMessageType('StatusRequest', (_message.Message,), {
  'DESCRIPTOR' : _STATUSREQUEST,
  '__module__' : 'qxdm_pb2'
  # @@protoc_insertion_point(class_scope:StatusRequest)
  })
_sym_db.RegisterMessage(StatusRequest)

StatusResponse = _reflection.GeneratedProtocolMessageType('StatusResponse', (_message.Message,), {
  'DESCRIPTOR' : _STATUSRESPONSE,
  '__module__' : 'qxdm_pb2'
  # @@protoc_insertion_point(class_scope:StatusResponse)
  })
_sym_db.RegisterMessage(StatusResponse)



_QXDM = _descriptor.ServiceDescriptor(
  name='QXDM',
  full_name='QXDM',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=609,
  serialized_end=919,
  methods=[
  _descriptor.MethodDescriptor(
    name='Connect',
    full_name='QXDM.Connect',
    index=0,
    containing_service=None,
    input_type=_CONNECTREQUEST,
    output_type=_CONNECTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Disconnect',
    full_name='QXDM.Disconnect',
    index=1,
    containing_service=None,
    input_type=_DISCONNECTREQUEST,
    output_type=_DISCONNECTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='StartLog',
    full_name='QXDM.StartLog',
    index=2,
    containing_service=None,
    input_type=_STARTLOGREQUEST,
    output_type=_STARTLOGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SaveLog',
    full_name='QXDM.SaveLog',
    index=3,
    containing_service=None,
    input_type=_SAVELOGREQUEST,
    output_type=_SAVELOGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ParseLog',
    full_name='QXDM.ParseLog',
    index=4,
    containing_service=None,
    input_type=_PARSELOGREQUEST,
    output_type=_PARSELOGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Status',
    full_name='QXDM.Status',
    index=5,
    containing_service=None,
    input_type=_STATUSREQUEST,
    output_type=_STATUSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_QXDM)

DESCRIPTOR.services_by_name['QXDM'] = _QXDM

# @@protoc_insertion_point(module_scope)
